In [2]:
import pandas as pd

data = [
    ["alice", 25],
    ["bob", 30],
    ["charlie", 35]
]

df = pd.DataFrame(data, columns=["Name","Age"])
print(df)

      Name  Age
0    alice   25
1      bob   30
2  charlie   35

In [3]:
data

[['alice', 25], ['bob', 30], ['charlie', 35]]

In [7]:
pd.DataFrame(data, columns=["Name","Marks"])

      Name  Marks
0    alice     25
1      bob     30
2  charlie     35

In [10]:
data= {"a":[1,2,3], "b":[33,44,55]}

In [12]:
df=pd.DataFrame(data)

In [13]:
data

{'a': [1, 2, 3], 'b': [33, 44, 55]}

In [14]:
df

   a   b
0  1  33
1  2  44
2  3  55

In [15]:
import numpy as np

In [16]:
arr=np.array([[1,2],[5,6]])

In [18]:
df=pd.DataFrame(arr,columns=["A","B"])

In [19]:
df

   A  B
0  1  2
1  5  6

In [21]:
df=pd.read_excel("data.xlsx")

In [22]:
df

      Name School  Age
0     RUDR    BFS   32
1    ROHAN    KSL   23
2    DAKSH    JHL   24
3  VANSHUL    LDS   12
4   SATWIK    IFD   21
5  KRISHNA    OSA   65
6     ANUJ   CFER   76
7  PRATHAM    DES   54
8     TARA    SEE   44

In [23]:
df=pd.read_csv("data.csv")

In [24]:
df

      Name School  Age
0     RUDR    BFS   32
1    ROHAN    KSL   23
2    DAKSH    JHL   24
3  VANSHUL    LDS   12
4   SATWIK    IFD   21
5  KRISHNA    OSA   65
6     ANUJ   CFER   76
7  PRATHAM    DES   54
8     TARA    SEE   44

In [26]:
df=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [27]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [29]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [30]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [32]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [34]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [35]:
df.shape

(244, 7)