In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df["Actor"]

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df[["Actor","IMDb"]]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [7]:
df.loc[6]

Actor                   Rajkummar Rao
Film                            Stree
Year                             2018
Genre                   Horror Comedy
BoxOffice(INR Crore)              180
IMDb                              7.5
Name: 6, dtype: object

In [8]:
df.iloc[6]

Actor                   Rajkummar Rao
Film                            Stree
Year                             2018
Genre                   Horror Comedy
BoxOffice(INR Crore)              180
IMDb                              7.5
Name: 6, dtype: object

In [9]:
df.loc[8,'IMDb']

np.float64(7.0)

In [10]:
df.iloc[7,4]

np.int64(475)

In [11]:
df.iloc[0,2]

np.int64(2023)

In [12]:
df.loc[0:2,["Actor","Genre"]]

            Actor      Genre
0  Shah Rukh Khan     Action
1     Salman Khan     Action
2      Aamir Khan  Biography

In [13]:
df.iloc[0:2,0:3]

            Actor             Film  Year
0  Shah Rukh Khan          Pathaan  2023
1     Salman Khan  Tiger Zinda Hai  2017

In [14]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [15]:
df.iat[0,1]

'Pathaan'

In [18]:
df[df["IMDb"]>7]

0         Shah Rukh Khan
2             Aamir Khan
5     Ayushmann Khurrana
6          Rajkummar Rao
11         Vicky Kaushal
Name: Actor, dtype: object

In [22]:
df[(df["IMDb"]>6) & (df["Year"]>2020)]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [24]:
df.query("Year>2019 and IMDb>6")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [29]:
df.query("`BoxOffice(INR Crore)`==1050")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2