In [7]:
import pandas as pd

In [19]:
employees = pd.DataFrame({
    "EmpID":[1,2,3],
    "Name":["Alice","Bob","John"],
    "DeptID":[10,20,30]
})
departments = pd.DataFrame({
    "DeptID":[10,20,40],
    "DeptName":["HR","Engineering","Marketing"]
})

In [20]:
employees

   EmpID   Name  DeptID
0      1  Alice      10
1      2    Bob      20
2      3   John      30

In [21]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [22]:
pd.merge(employees, departments, on="DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [23]:
pd.merge(employees, departments, on="DeptID",how="left")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering
2      3   John      30          NaN

In [24]:
pd.merge(employees, departments, on="DeptID",how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [25]:
pd.merge(employees, departments, on="DeptID",how="outer")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    3.0   John      30          NaN
3    NaN    NaN      40    Marketing

In [26]:
pd.concat([employees,Departments])

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10          NaN
1    2.0    Bob      20          NaN
2    3.0   John      30          NaN
0    NaN    NaN      10           HR
1    NaN    NaN      20  Engineering
2    NaN    NaN      40    Marketing

In [27]:
pd.concat([employees,Departments],axis=1
         )

   EmpID   Name  DeptID  DeptID     DeptName
0      1  Alice      10      10           HR
1      2    Bob      20      20  Engineering
2      3   John      30      40    Marketing